# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: antoine.blanchard@gmail.com
full_name: Antoine Blanchard
gh_action_docs_preview: true
gh_action_pypi: true
github_org: grant-applications-data
license: MIT
project_description: A minimal data schema to increase the transparency of grant applications,
    while protecting their confidentiality and the privacy of their applicants.
project_name: miga
project_slug: miga

